# Generated by Django 2.2 on 2021-02-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
