# Generated by Django 3.1.6 on 2021-02-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210204_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doc',
                'verbose_name_plural': 'Docs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='doc',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='api.doc'),
        ),
    ]
